	.align 2
voicegroup507::
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_pmd_pcm_1E8664C, 0, 0, 15, 0 @ 0 | Wave |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 1 | Square-1 | --
	voice_keysplit voicegroup518, KeySplitTablePMD03 @ 2 | Multi |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E97814, 29, 204, 154, 204 @ 3 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1EAAA1C, 255, 249, 25, 226 @ 4 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1EAAA1C, 255, 0, 255, 0 @ 5 | Direct |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 6 | Square-1 | --
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1EACEDC, 255, 0, 255, 0 @ 7 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1EADC80, 255, 0, 255, 216 @ 8 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1EB0490, 255, 0, 255, 127 @ 9 | Direct |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 10 | Square-1 | --
	voice_keysplit_all voicegroup506 @ 11 | Drum |
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_pmd_pcm_1EB2318, 255, 0, 255, 216 @ 12 | Direct |
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_pmd_pcm_1EB2D60, 255, 0, 255, 216 @ 13 | Direct |
	voice_directsound_no_resample 66, 64, DirectSoundWaveData_pmd_pcm_1EB3B34, 255, 0, 255, 216 @ 14 | Direct |
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_pmd_pcm_1EB5878, 255, 0, 255, 216 @ 15 | Direct |
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_pmd_pcm_1EB691C, 255, 0, 255, 216 @ 16 | Direct |
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_pmd_pcm_1EB7E90, 255, 0, 255, 216 @ 17 | Direct |
	voice_noise_alt 60, 0, 0, 0, 1, 0, 0 @ 18 | Noise |
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_pmd_pcm_1EB94B8, 255, 0, 255, 127 @ 19 | Direct |
	voice_noise_alt 60, 0, 0, 0, 1, 0, 0 @ 20 | Noise |
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_pmd_pcm_1EBA298, 255, 0, 255, 165 @ 21 | Direct |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 22 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 23 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 24 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 25 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 26 | Square-1 | --
	voice_noise_alt 60, 0, 0, 0, 2, 0, 0 @ 27 | Noise |
	voice_noise_alt 60, 0, 0, 0, 2, 6, 0 @ 28 | Noise |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 29 | Square-1 | --
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_pmd_pcm_1EBA840, 255, 0, 255, 216 @ 30 | Direct |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 31 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 32 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 33 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 34 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 35 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 36 | Square-1 | --
	voice_directsound_no_resample 60, 44, DirectSoundWaveData_pmd_pcm_1EBB32C, 255, 0, 255, 204 @ 37 | Direct |
	voice_directsound_no_resample 60, 84, DirectSoundWaveData_pmd_pcm_1EBBDCC, 255, 0, 255, 204 @ 38 | Direct |
	voice_directsound_no_resample 60, 44, DirectSoundWaveData_pmd_pcm_1EBC208, 255, 0, 255, 204 @ 39 | Direct |
	voice_directsound_no_resample 60, 84, DirectSoundWaveData_pmd_pcm_1EBD1D4, 255, 0, 255, 204 @ 40 | Direct |
	voice_directsound_no_resample 60, 84, DirectSoundWaveData_pmd_pcm_1EBE6E0, 255, 0, 255, 216 @ 41 | Direct |
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_pmd_pcm_1EACEDC, 255, 0, 255, 216 @ 42 | Direct |
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_pmd_pcm_1EBF45C, 255, 0, 255, 216 @ 43 | Direct |
	voice_directsound_no_resample 60, 44, DirectSoundWaveData_pmd_pcm_1EC0F20, 255, 0, 255, 216 @ 44 | Direct |
	voice_noise_alt 60, 0, 0, 0, 1, 0, 0 @ 45 | Noise |
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_pmd_pcm_1EC1FF4, 255, 0, 255, 216 @ 46 | Direct |
	voice_directsound_no_resample 60, 44, DirectSoundWaveData_pmd_pcm_1EC2EC4, 255, 0, 255, 216 @ 47 | Direct |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 48 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 49 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 50 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 51 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 52 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 53 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 54 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 55 | Square-1 | --
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_pmd_pcm_1EC3F98, 255, 249, 0, 216 @ 56 | Direct |
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_pmd_pcm_1EC4EA0, 255, 226, 0, 216 @ 57 | Direct |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 58 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 59 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 60 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 61 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 62 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 63 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 64 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 65 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 66 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 67 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 68 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 69 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 70 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 71 | Square-1 | --
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_pmd_pcm_1EB2318, 255, 0, 255, 216 @ 72 | Direct |
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_pmd_pcm_1EB2D60, 255, 0, 255, 216 @ 73 | Direct |
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_pmd_pcm_1EC5934, 255, 0, 255, 216 @ 74 | Direct |
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_pmd_pcm_1EB94B8, 255, 0, 255, 127 @ 75 | Direct |
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_pmd_pcm_1EC6C50, 255, 0, 255, 216 @ 76 | Direct |
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_pmd_pcm_1EC7C70, 255, 0, 255, 216 @ 77 | Direct |
	voice_noise_alt 60, 0, 0, 0, 1, 0, 0 @ 78 | Noise |
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_pmd_pcm_1EC93A4, 255, 0, 255, 216 @ 79 | Direct |
	voice_noise_alt 60, 0, 0, 0, 1, 0, 0 @ 80 | Noise |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 81 | Square-1 | --
	voice_directsound_no_resample 68, 64, DirectSoundWaveData_pmd_pcm_1EB5878, 255, 0, 255, 216 @ 82 | Direct |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 83 | Square-1 | --
	voice_directsound_no_resample 68, 34, DirectSoundWaveData_pmd_pcm_1ECAAD4, 64, 226, 0, 0 @ 84 | Direct |
	voice_directsound_no_resample 68, 64, DirectSoundWaveData_pmd_pcm_1ECAAD4, 255, 226, 0, 0 @ 85 | Direct |
	voice_directsound_no_resample 68, 94, DirectSoundWaveData_pmd_pcm_1ECAAD4, 64, 226, 0, 0 @ 86 | Direct |
	voice_noise_alt 60, 0, 0, 0, 2, 0, 0 @ 87 | Noise |
	voice_noise_alt 60, 0, 0, 0, 2, 6, 0 @ 88 | Noise |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 89 | Square-1 | --
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_pmd_pcm_1EBA840, 255, 0, 255, 216 @ 90 | Direct |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 91 | Square-1 | --
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_pmd_pcm_1ECBB2C, 255, 0, 255, 216 @ 92 | Direct |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 93 | Square-1 | --
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_pmd_pcm_1EBE6E0, 255, 0, 255, 216 @ 94 | Direct |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 95 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 96 | Square-1 | --
	voice_directsound_no_resample 60, 44, DirectSoundWaveData_pmd_pcm_1EBB32C, 255, 0, 255, 204 @ 97 | Direct |
	voice_directsound_no_resample 60, 84, DirectSoundWaveData_pmd_pcm_1EBBDCC, 255, 0, 255, 204 @ 98 | Direct |
	voice_directsound_no_resample 60, 44, DirectSoundWaveData_pmd_pcm_1EBC208, 255, 0, 255, 204 @ 99 | Direct |
	voice_directsound_no_resample 60, 84, DirectSoundWaveData_pmd_pcm_1EBD1D4, 255, 0, 255, 204 @ 100 | Direct |
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_pmd_pcm_1EADC80, 255, 0, 255, 216 @ 101 | Direct |
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_pmd_pcm_1EB0490, 255, 0, 255, 127 @ 102 | Direct |
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_pmd_pcm_1ECC450, 255, 0, 255, 0 @ 103 | Direct |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 104 | Square-1 | --
	voice_noise_alt 60, 0, 0, 0, 1, 0, 0 @ 105 | Noise |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 106 | Square-1 | --
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_pmd_pcm_1EACEDC, 255, 0, 255, 216 @ 107 | Direct |
	voice_directsound_no_resample 60, 44, DirectSoundWaveData_pmd_pcm_1EBF45C, 255, 0, 255, 216 @ 108 | Direct |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 109 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 110 | Square-1 | --
	voice_directsound_no_resample 60, 84, DirectSoundWaveData_pmd_pcm_1EC0F20, 255, 0, 255, 216 @ 111 | Direct |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 112 | Square-1 | --
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_pmd_pcm_1EC1FF4, 255, 0, 255, 216 @ 113 | Direct |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 114 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 115 | Square-1 | --
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_pmd_pcm_1EC3F98, 255, 249, 0, 165 @ 116 | Direct |
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_pmd_pcm_1EC4EA0, 255, 226, 0, 165 @ 117 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1ECCC08, 51, 0, 103, 127 @ 118 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1ECD2B4, 51, 0, 103, 127 @ 119 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1ECCC08, 51, 0, 255, 127 @ 120 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1ECD2B4, 51, 0, 255, 127 @ 121 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1ECD4E8, 64, 0, 255, 149 @ 122 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1ECF9BC, 64, 0, 255, 149 @ 123 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1ED2850, 64, 0, 255, 149 @ 124 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1ED48CC, 255, 249, 128, 216 @ 125 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1ED5C70, 85, 235, 77, 216 @ 126 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1ED68F0, 85, 216, 25, 216 @ 127 | Direct |
