	.align 2
voicegroup504::
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E88420, 64, 165, 206, 226 		@ 0 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E899A0, 64, 204, 103, 188 		@ 1 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E8FEEC, 64, 242, 51, 216 			@ 2 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E88420, 64, 235, 25, 239 			@ 3 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E8B520, 51, 188, 206, 226 		@ 4 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E88420, 255, 188, 77, 204 		@ 5 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E8C5DC, 255, 0, 255, 149 			@ 6 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E8D478, 255, 165, 154, 165 		@ 7 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E8E6D8, 255, 249, 25, 204 		@ 8 | Direct |
	voice_keysplit voicegroup514, KeySplitTablePMD07 										@ 9 | Direct | Multi |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E8FEEC, 255, 242, 128, 216 		@ 10 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E90FA0, 255, 0, 255, 127 			@ 11 | Direct |
	voice_keysplit voicegroup513, KeySplitTablePMD06 										@ 12 | Multi |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E922E4, 255, 0, 255, 165 			@ 13 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E926DC, 128, 235, 255, 242 		@ 14 | Direct |
	voice_keysplit voicegroup517, KeySplitTablePMD07 										@ 15 | Multi |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E94D0C, 255, 0, 255, 127 			@ 16 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E94D0C, 51, 216, 128, 149 		@ 17 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E97110, 255, 0, 255, 127 			@ 18 | Direct |
	voice_keysplit voicegroup508, KeySplitTablePMD02 										@ 19 | Direct | Multi |
	voice_keysplit voicegroup515, KeySplitTablePMD01 										@ 20 | Direct | Multi |
	voice_keysplit voicegroup509, KeySplitTablePMD02 										@ 21 | Direct | Multi |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E97814, 15, 0, 255, 204 			@ 22 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1EA8B60, 19, 165, 206, 216 		@ 23 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E98378, 37, 0, 255, 0 			@ 24 | Direct |
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_pmd_pcm_1E8654C, 0, 0, 15, 0 	@ 25 | Wave |
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_pmd_pcm_1E8655C, 0, 0, 15, 0 	@ 26 | Wave |
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_pmd_pcm_1E8656C, 0, 0, 15, 0 	@ 27 | Wave |
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_pmd_pcm_1E8657C, 0, 0, 15, 0 	@ 28 | Wave |
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_pmd_pcm_1E8658C, 0, 0, 15, 0 	@ 29 | Wave |
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_pmd_pcm_1E8659C, 0, 0, 15, 0 	@ 30 | Wave |
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_pmd_pcm_1E865AC, 0, 0, 15, 0 	@ 31 | Wave |
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_pmd_pcm_1E865BC, 0, 0, 15, 0 	@ 32 | Wave |
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_pmd_pcm_1E865CC, 0, 0, 15, 0 	@ 33 | Wave |
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_pmd_pcm_1E865DC, 0, 0, 15, 0 	@ 34 | Wave |
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_pmd_pcm_1E865EC, 0, 0, 15, 0 	@ 35 | Wave |
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_pmd_pcm_1E865FC, 0, 0, 15, 0 	@ 36 | Wave |
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_pmd_pcm_1E8660C, 0, 0, 15, 0 	@ 37 | Wave |
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_pmd_pcm_1E8661C, 0, 0, 15, 0 	@ 38 | Wave |
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_pmd_pcm_1E8662C, 0, 0, 15, 0 	@ 39 | Wave |
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_pmd_pcm_1E8663C, 0, 0, 15, 0 	@ 40 | Wave |
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_pmd_pcm_1E8659C, 0, 0, 15, 0 	@ 41 | Wave |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E99740, 255, 216, 128, 165 		@ 42 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E9AF9C, 255, 188, 103, 165 		@ 43 | Direct |
	voice_keysplit voicegroup519, KeySplitTablePMD08 										@ 44 | Direct | Multi |
	voice_keysplit voicegroup510, KeySplitTablePMD03 										@ 45 | Direct | Multi |
	voice_keysplit voicegroup511, KeySplitTablePMD04 										@ 46 | Direct | Multi |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E9AF9C, 255, 188, 103, 0 			@ 47 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E8E6D8, 255, 249, 25, 0 			@ 48 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E9AF9C, 255, 188, 103, 216 		@ 49 | Direct |
	voice_keysplit voicegroup516, KeySplitTablePMD06 										@ 50 | Multi |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E9BD98, 255, 235, 180, 188 		@ 51 | Direct |
	voice_square_2_alt 60, 0, 2, 0, 0, 7, 0 												@ 52 | Square-2 |
	voice_square_1_alt 60, 0, 0, 2, 0, 0, 7, 0 												@ 53 | Square-1 |
	voice_square_1_alt 60, 0, 0, 1, 0, 2, 3, 5 												@ 54 | Square-1 |
	voice_square_1_alt 60, 0, 0, 1, 0, 2, 3, 5 												@ 55 | Square-1 |
	voice_square_2_alt 60, 0, 0, 0, 2, 3, 5 												@ 56 | Square-2 |
	voice_square_1_alt 60, 0, 0, 0, 0, 2, 3, 5 												@ 57 | Square-1 |
	voice_square_2_alt 60, 0, 2, 0, 0, 7, 3 												@ 58 | Square-2 |
	voice_square_1_alt 60, 0, 0, 2, 0, 0, 7, 3 												@ 59 | Square-1 |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E9E4CC, 255, 165, 154, 149 		@ 60 | Direct |
	voice_square_2_alt 60, 0, 2, 2, 0, 7, 4 												@ 61 | Square-2 |
	voice_square_1_alt 60, 0, 0, 2, 2, 0, 7, 4 												@ 62 | Square-1 |
	voice_square_2_alt 60, 0, 2, 0, 0, 7, 3 												@ 63 | Square-2 |
	voice_square_1_alt 60, 0, 0, 1, 0, 0, 7, 3 												@ 64 | Square-1 |
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_pmd_pcm_1E8660C, 0, 0, 15, 1 	@ 65 | Wave |
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_pmd_pcm_1E8654C, 0, 0, 15, 2 	@ 66 | Wave |
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_pmd_pcm_1E8655C, 0, 0, 15, 0 	@ 67 | Wave |
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_pmd_pcm_1E8656C, 0, 0, 15, 2 	@ 68 | Wave |
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_pmd_pcm_1E8656C, 0, 0, 15, 4 	@ 69 | Wave |
	voice_square_2_alt 60, 0, 1, 0, 0, 7, 3 												@ 70 | Square-2 |
	voice_square_1_alt 60, 0, 0, 1, 0, 0, 7, 3 												@ 71 | Square-1 |
	voice_keysplit voicegroup520, KeySplitTablePMD03 										@ 72 | Direct | Multi |
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_pmd_pcm_1E8655C, 0, 0, 15, 0 	@ 73 | Wave |
	voice_square_2_alt 60, 0, 3, 0, 2, 3, 5 												@ 74 | Square-2 |
	voice_square_1_alt 60, 0, 0, 3, 0, 2, 3, 5 												@ 75 | Square-1 |
	voice_keysplit voicegroup512, KeySplitTablePMD05 										@ 76 | Direct | Multi |
	voice_square_2_alt 60, 0, 2, 0, 0, 7, 3 												@ 77 | Square-2 |
	voice_square_1_alt 60, 0, 0, 2, 0, 0, 7, 3 												@ 78 | Square-1 |
	voice_square_2_alt 60, 0, 3, 0, 2, 3, 5 												@ 79 | Square-2 |
	voice_square_1_alt 60, 0, 0, 3, 0, 2, 3, 5 												@ 80 | Square-1 |
	voice_square_2_alt 60, 0, 2, 2, 0, 7, 3 												@ 81 | Square-2 |
	voice_square_1_alt 60, 0, 0, 2, 2, 0, 7, 3 												@ 82 | Square-1 |
	voice_square_2_alt 60, 0, 2, 1, 1, 15, 3 												@ 83 | Square-2 |
	voice_square_1_alt 60, 0, 0, 2, 1, 1, 15, 3 											@ 84 | Square-1 |
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_pmd_pcm_1E8653C, 2, 0, 15, 2 	@ 85 | Wave |
	voice_square_1_alt 60, 0, 0, 1, 1, 1, 15, 0 											@ 86 | Square-1 |
	voice_square_2_alt 60, 0, 2, 0, 1, 15, 0 												@ 87 | Square-2 |
	voice_square_1_alt 60, 0, 0, 2, 0, 1, 15, 0 											@ 88 | Square-1 |
	voice_square_2_alt 60, 0, 2, 0, 0, 15, 0 												@ 89 | Square-2 |
	voice_square_1_alt 60, 0, 0, 2, 0, 0, 15, 0 											@ 90 | Square-1 |
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_pmd_pcm_1E8653C, 0, 0, 15, 2 	@ 91 | Wave |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E9F53C, 255, 0, 255, 188 			@ 92 | Direct |
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_pmd_pcm_1E8659C, 0, 0, 15, 0 	@ 93 | Wave |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1EA02C8, 22, 188, 206, 204 		@ 94 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1EA02C8, 255, 188, 206, 204 		@ 95 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1EA24B8, 255, 245, 0, 204 			@ 96 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1EA02C8, 255, 188, 206, 115 		@ 97 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E97814, 64, 204, 154, 204 		@ 98 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1EA8B60, 255, 165, 206, 188 		@ 99 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1EA345C, 255, 216, 0, 165 			@ 100 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1EA40B0, 255, 0, 255, 127 			@ 101 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1EA421C, 255, 188, 154, 127 		@ 102 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1EA536C, 64, 0, 0, 165 			@ 103 | Direct |
	voice_square_2_alt 60, 0, 0, 0, 0, 15, 0 												@ 104 | Square-2 |
	voice_square_2_alt 60, 0, 1, 0, 0, 15, 0 												@ 105 | Square-2 |
	voice_square_1_alt 60, 0, 0, 0, 0, 0, 15, 0 											@ 106 | Square-1 |
	voice_square_1_alt 60, 0, 0, 1, 0, 0, 15, 0 											@ 107 | Square-1 |
	voice_square_2_alt 60, 0, 1, 0, 0, 15, 0 												@ 108 | Square-2 |
	voice_square_2_alt 60, 0, 2, 0, 0, 15, 0 												@ 109 | Square-2 |
	voice_square_1_alt 60, 0, 0, 1, 0, 0, 15, 0 											@ 110 | Square-1 |
	voice_square_1_alt 60, 0, 0, 2, 0, 0, 15, 0 											@ 111 | Square-1 |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E9E4CC, 255, 226, 103, 188 		@ 112 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1EA8B60, 255, 188, 180, 188 		@ 113 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1EA02C8, 255, 188, 206, 226 		@ 114 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E97814, 255, 204, 154, 204 		@ 115 | Direct |
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_pmd_pcm_1E8664C, 0, 0, 15, 0 	@ 116 | Wave |
	voice_square_1_alt 60, 0, 0, 2, 0, 0, 15, 0 											@ 117 | Unused
	voice_keysplit voicegroup518, KeySplitTablePMD03 										@ 118 | Direct | Multi |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E97814, 29, 204, 154, 204 		@ 119 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1EAAA1C, 255, 249, 25, 226 		@ 120 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1EAAA1C, 255, 0, 255, 0 			@ 121 | Direct |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 												@ 122 | Unused
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1EACEDC, 255, 0, 255, 0 			@ 123 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1EADC80, 255, 0, 255, 216 			@ 124 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1EB0490, 255, 0, 255, 127 			@ 125 | Direct |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 												@ 126 | Unused
	voice_keysplit_all voicegroup506 														@ 127 | Direct | Drum | PMD Drum 1

