	.align 2
voicegroup505::
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E922E4, 255, 0, 255, 0 			@ 0 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E90FA0, 255, 0, 255, 0 			@ 1 | Direct |
	voice_keysplit voicegroup521, KeySplitTablePMD07 										@ 2 | Direct | Multi |
	voice_keysplit voicegroup522, KeySplitTablePMD06 										@ 3 | Direct | Multi |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1EA02C8, 255, 188, 206, 188 		@ 4 | Direct |
	voice_keysplit voicegroup523, KeySplitTablePMD05 										@ 5 | Direct | Multi |
	voice_keysplit voicegroup524, KeySplitTablePMD04 										@ 6 | Direct | Multi |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E8D478, 255, 165, 154, 165 		@ 7 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E94D0C, 255, 0, 255, 0 			@ 8 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E94D0C, 255, 165, 0, 127 			@ 9 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1EA24B8, 255, 226, 0, 127 			@ 10 | Direct |
	voice_keysplit voicegroup525, KeySplitTablePMD06 										@ 11 | Direct | Multi |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1EA02C8, 255, 188, 180, 127 		@ 12 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1EE6B60, 255, 188, 180, 127 		@ 13 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E8E6D8, 255, 249, 25, 204 		@ 14 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E9E4CC, 13, 0, 255, 127 			@ 15 | Direct |
	voice_keysplit voicegroup526, KeySplitTablePMD09 										@ 16 | Direct | Multi |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E8C5DC, 255, 0, 255, 149 			@ 17 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E97110, 255, 0, 255, 127 			@ 18 | Direct |
	voice_keysplit voicegroup527, KeySplitTablePMD02 										@ 19 | Direct | Multi |
	voice_keysplit voicegroup528, KeySplitTablePMD02 										@ 20 | Direct | Multi |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E99740, 255, 0, 255, 0 			@ 21 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E98378, 37, 0, 255, 0 			@ 22 | Direct |
	voice_keysplit voicegroup529, KeySplitTablePMD01 										@ 23 | Direct | Multi |
	voice_keysplit voicegroup530, KeySplitTablePMD08 										@ 24 | Direct | Multi |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E9AF9C, 255, 188, 103, 165 		@ 25 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1EA536C, 64, 249, 0, 165 			@ 26 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E899A0, 64, 204, 103, 188 		@ 27 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E926DC, 64, 235, 255, 0 			@ 28 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E9BD98, 255, 235, 255, 188 		@ 29 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E9AF9C, 64, 0, 103, 0 			@ 30 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E922E4, 64, 0, 255, 0 			@ 31 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1EE6CB8, 255, 204, 51, 165 		@ 32 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E9F53C, 255, 0, 255, 127 			@ 33 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E8E6D8, 255, 204, 51, 0 			@ 34 | Direct |
	voice_keysplit voicegroup526, KeySplitTablePMD10 										@ 35 | Multi |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 												@ 36 | Unused
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 												@ 37 | Unused
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 												@ 38 | Unused
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 												@ 39 | Unused
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1EE714C, 64, 255, 0, 0 			@ 40 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1EE8C98, 37, 0, 255, 0 			@ 41 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1EEB4C4, 37, 0, 255, 0 			@ 42 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1EED93C, 37, 0, 255, 0 			@ 43 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1EEFFCC, 37, 0, 255, 0 			@ 44 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1EF14D8, 64, 0, 255, 0 			@ 45 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1EFA50C, 64, 249, 25, 127 			@ 46 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E926DC, 128, 235, 255, 242 		@ 47 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1EF4248, 64, 0, 255, 0 			@ 48 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1EF5698, 255, 0, 255, 127 			@ 49 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E8FEEC, 255, 0, 255, 127 			@ 50 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E8FEEC, 255, 216, 0, 127 			@ 51 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E88420, 255, 188, 77, 242 		@ 52 | Direct |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 												@ 53 | Unused
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 												@ 54 | Unused
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1EA345C, 255, 216, 0, 165 			@ 55 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1EA40B0, 255, 0, 255, 127 			@ 56 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1EA421C, 255, 188, 154, 127 		@ 57 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E97814, 15, 0, 255, 204 			@ 58 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1EA8B60, 19, 165, 206, 216 		@ 59 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1EA8B60, 26, 165, 206, 0 			@ 60 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E97814, 26, 0, 255, 204 			@ 61 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1EA8B60, 37, 165, 206, 204 		@ 62 | Direct |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 												@ 63 | Unused
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 												@ 64 | Unused
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 												@ 65 | Unused
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 												@ 66 | Unused
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 												@ 67 | Unused
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 												@ 68 | Unused
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 												@ 69 | Unused
	voice_square_2_alt 60, 0, 2, 0, 0, 15, 0 												@ 70 | Square-2 |
	voice_square_2_alt 60, 0, 1, 0, 0, 15, 0 												@ 71 | Square-2 |
	voice_square_2_alt 60, 0, 0, 0, 0, 15, 0 												@ 72 | Square-2 |
	voice_square_2_alt 60, 0, 2, 0, 1, 0, 1 												@ 73 | Square-2 |
	voice_square_2_alt 60, 0, 2, 0, 2, 1, 0 												@ 74 | Square-2 |
	voice_square_2_alt 60, 0, 1, 0, 1, 0, 1 												@ 75 | Square-2 |
	voice_square_2_alt 60, 0, 1, 0, 2, 1, 0 												@ 76 | Square-2 |
	voice_square_2_alt 60, 0, 0, 0, 1, 0, 1 												@ 77 | Square-2 |
	voice_square_2_alt 60, 0, 0, 0, 2, 1, 0 												@ 78 | Square-2 |
	voice_square_2_alt 60, 0, 2, 0, 3, 3, 0 												@ 79 | Square-2 |
	voice_square_1_alt 60, 0, 0, 2, 1, 3, 12, 1 											@ 80 | Square-1 |
	voice_square_1_alt 60, 0, 0, 2, 1, 0, 15, 0 											@ 81 | Square-1 |
	voice_square_1_alt 60, 0, 0, 2, 0, 0, 15, 0 											@ 82 | Square-1 |
	voice_square_1_alt 60, 0, 0, 1, 0, 0, 15, 0 											@ 83 | Square-1 |
	voice_square_1_alt 60, 0, 0, 0, 0, 0, 15, 0 											@ 84 | Square-1 |
	voice_square_1_alt 60, 0, 0, 2, 0, 1, 0, 1 												@ 85 | Square-1 |
	voice_square_1_alt 60, 0, 0, 2, 0, 2, 1, 0 												@ 86 | Square-1 |
	voice_square_1_alt 60, 0, 0, 1, 0, 1, 0, 1 												@ 87 | Square-1 |
	voice_square_1_alt 60, 0, 0, 1, 0, 2, 1, 0 												@ 88 | Square-1 |
	voice_square_1_alt 60, 0, 0, 0, 0, 1, 0, 1 												@ 89 | Square-1 |
	voice_square_1_alt 60, 0, 0, 0, 0, 2, 1, 0 												@ 90 | Square-1 |
	voice_square_2_alt 60, 0, 2, 1, 1, 0, 0 												@ 91 | Square-2 |
	voice_square_2_alt 60, 0, 1, 1, 1, 0, 0 												@ 92 | Square-2 |
	voice_square_2_alt 60, 0, 0, 1, 1, 0, 0 												@ 93 | Square-2 |
	voice_square_1_alt 60, 0, 0, 2, 1, 1, 0, 0 												@ 94 | Square-1 |
	voice_square_1_alt 60, 0, 0, 1, 1, 1, 0, 0 												@ 95 | Square-1 |
	voice_square_1_alt 60, 0, 0, 0, 1, 1, 0, 0 												@ 96 | Square-1 |
	voice_square_2_alt 60, 0, 2, 1, 3, 12, 1 												@ 97 | Square-2 |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 												@ 98 | Unused
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 												@ 99 | Unused
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_pmd_pcm_1E8655C, 0, 0, 15, 0 	@ 100 | Wave |
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_pmd_pcm_1E8663C, 0, 0, 15, 0 	@ 101 | Wave |
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_pmd_pcm_1E8654C, 0, 0, 15, 0 	@ 102 | Wave |
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_pmd_pcm_1E8657C, 0, 0, 15, 0 	@ 103 | Wave |
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_pmd_pcm_1E8664C, 0, 0, 15, 0 	@ 104 | Wave |
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_pmd_pcm_1E865EC, 0, 0, 15, 0 	@ 105 | Wave |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 												@ 106 | Unused
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 												@ 107 | Unused
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 												@ 108 | Unused
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 												@ 109 | Unused
	voice_noise_alt 60, 0, 0, 1, 0, 7, 0 													@ 110 | Noise |
	voice_noise_alt 60, 0, 0, 0, 4, 3, 2 													@ 111 | Noise |
	voice_noise_alt 60, 0, 0, 0, 5, 0, 0 													@ 112 | Noise |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 												@ 113 | Unused
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 												@ 114 | Unused
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1ECAAD4, 255, 0, 255, 0 			@ 115 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1EADC80, 255, 0, 255, 127 			@ 116 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1ECBB2C, 255, 0, 255, 127 			@ 117 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1ECAAD4, 10, 0, 255, 127 			@ 118 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1EACEDC, 255, 0, 255, 127 			@ 119 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1EBA840, 255, 0, 255, 127 			@ 120 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1EAAA1C, 255, 242, 0, 127 			@ 121 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1EAAA1C, 255, 0, 255, 0 			@ 122 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1ECAAD4, 255, 0, 255, 242 			@ 123 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1EB94B8, 255, 0, 255, 127 			@ 124 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1ECC450, 255, 0, 255, 0 			@ 125 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1ECAAD4, 255, 255, 0, 204 			@ 126 | Direct |
	voice_keysplit_all voicegroup507 														@ 127 | Direct | Drum | PMD Drum 2
