	.align 2
voicegroup506::
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E9F53C, 255, 0, 255, 188 @ 0 | Direct |
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_pmd_pcm_1E8659C, 0, 0, 15, 0 @ 1 | Wave |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1EA02C8, 22, 188, 206, 204 @ 2 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1EA02C8, 255, 188, 206, 204 @ 3 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1EA24B8, 255, 245, 0, 204 @ 4 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1EA02C8, 255, 188, 206, 115 @ 5 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E97814, 64, 204, 154, 204 @ 6 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1EA8B60, 255, 165, 206, 188 @ 7 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1EA345C, 255, 216, 0, 165 @ 8 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1EA40B0, 255, 0, 255, 127 @ 9 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1EA421C, 255, 188, 154, 127 @ 10 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1EA536C, 64, 0, 0, 165 @ 11 | Direct |
	voice_square_2_alt 60, 0, 0, 0, 0, 15, 0 @ 12 | Square-2 |
	voice_square_2_alt 60, 0, 1, 0, 0, 15, 0 @ 13 | Square-2 |
	voice_square_1_alt 60, 0, 0, 0, 0, 0, 15, 0 @ 14 | Square-1 |
	voice_square_1_alt 60, 0, 0, 1, 0, 0, 15, 0 @ 15 | Square-1 |
	voice_square_2_alt 60, 0, 1, 0, 0, 15, 0 @ 16 | Square-2 |
	voice_square_2_alt 60, 0, 2, 0, 0, 15, 0 @ 17 | Square-2 |
	voice_square_1_alt 60, 0, 0, 1, 0, 0, 15, 2 @ 18 | Square-1 |
	voice_square_1_alt 60, 0, 0, 1, 0, 0, 15, 2 @ 19 | Square-1 |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E9E4CC, 255, 226, 103, 188 @ 20 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1EA8B60, 255, 188, 180, 188 @ 21 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1EA02C8, 255, 188, 206, 226 @ 22 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E97814, 255, 204, 154, 204 @ 23 | Direct |
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_pmd_pcm_1E8664C, 0, 0, 15, 0 @ 24 | Wave |
	voice_square_1_alt 60, 0, 0, 2, 0, 0, 15, 0 @ 25 | Square-1 |
	voice_keysplit voicegroup518, KeySplitTablePMD03 @ 26 | Multi |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1E97814, 29, 204, 154, 204 @ 27 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1EAAA1C, 255, 249, 25, 226 @ 28 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1EAAA1C, 255, 0, 255, 0 @ 29 | Direct |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 30 | Square-1 | --
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1EACEDC, 255, 0, 255, 0 @ 31 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1EADC80, 255, 0, 255, 216 @ 32 | Direct |
	voice_directsound 60, 0, DirectSoundWaveData_pmd_pcm_1EB0490, 255, 0, 255, 127 @ 33 | Direct |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 34 | Square-1 | --
	voice_keysplit_all voicegroup506 @ 35 | Drum |
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_pmd_pcm_1EB2318, 255, 0, 255, 216 @ 36 | Direct |
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_pmd_pcm_1EB2D60, 255, 0, 255, 216 @ 37 | Direct |
	voice_directsound 66, 64, DirectSoundWaveData_pmd_pcm_1EB3B34, 255, 0, 255, 216 @ 38 | Direct |
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_pmd_pcm_1EB5878, 255, 0, 255, 216 @ 39 | Direct |
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_pmd_pcm_1EB691C, 255, 0, 255, 216 @ 40 | Direct |
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_pmd_pcm_1EB7E90, 255, 0, 255, 216 @ 41 | Direct |
	voice_noise_alt 60, 0, 0, 0, 1, 0, 0 @ 42 | Noise |
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_pmd_pcm_1EB94B8, 255, 0, 255, 127 @ 43 | Direct |
	voice_noise_alt 60, 0, 0, 0, 1, 0, 0 @ 44 | Noise |
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_pmd_pcm_1EBA298, 255, 0, 255, 165 @ 45 | Direct |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 46 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 47 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 48 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 49 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 50 | Square-1 | --
	voice_noise_alt 60, 0, 0, 0, 2, 0, 0 @ 51 | Noise |
	voice_noise_alt 60, 0, 0, 0, 2, 6, 0 @ 52 | Noise |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 53 | Square-1 | --
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_pmd_pcm_1EBA840, 255, 0, 255, 216 @ 54 | Direct |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 55 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 56 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 57 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 58 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 59 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 60 | Square-1 | --
	voice_directsound_no_resample 60, 44, DirectSoundWaveData_pmd_pcm_1EBB32C, 255, 0, 255, 204 @ 61 | Direct |
	voice_directsound_no_resample 60, 84, DirectSoundWaveData_pmd_pcm_1EBBDCC, 255, 0, 255, 204 @ 62 | Direct |
	voice_directsound_no_resample 60, 44, DirectSoundWaveData_pmd_pcm_1EBC208, 255, 0, 255, 204 @ 63 | Direct |
	voice_directsound_no_resample 60, 84, DirectSoundWaveData_pmd_pcm_1EBD1D4, 255, 0, 255, 204 @ 64 | Direct |
	voice_directsound_no_resample 60, 84, DirectSoundWaveData_pmd_pcm_1EBE6E0, 255, 0, 255, 216 @ 65 | Direct |
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_pmd_pcm_1EACEDC, 255, 0, 255, 216 @ 66 | Direct |
	voice_directsound_no_resample 60, 84, DirectSoundWaveData_pmd_pcm_1EBF45C, 255, 0, 255, 216 @ 67 | Direct |
	voice_directsound_no_resample 60, 44, DirectSoundWaveData_pmd_pcm_1EC0F20, 255, 0, 255, 216 @ 68 | Direct |
	voice_noise_alt 60, 0, 0, 0, 1, 0, 0 @ 69 | Noise |
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_pmd_pcm_1EC1FF4, 255, 0, 255, 216 @ 70 | Direct |
	voice_directsound_no_resample 60, 44, DirectSoundWaveData_pmd_pcm_1EC2EC4, 255, 0, 255, 216 @ 71 | Direct |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 72 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 73 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 74 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 75 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 76 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 77 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 78 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 79 | Square-1 | --
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_pmd_pcm_1EC3F98, 255, 249, 0, 216 @ 80 | Direct |
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_pmd_pcm_1EC4EA0, 255, 226, 0, 216 @ 81 | Direct |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 82 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 83 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 84 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 85 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 86 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 87 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 88 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 89 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 90 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 91 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 92 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 93 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 94 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 95 | Square-1 | --
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_pmd_pcm_1EB2318, 255, 0, 255, 216 @ 96 | Direct |
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_pmd_pcm_1EB2D60, 255, 0, 255, 216 @ 97 | Direct |
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_pmd_pcm_1EC5934, 255, 0, 255, 216 @ 98 | Direct |
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_pmd_pcm_1EB94B8, 255, 0, 255, 127 @ 99 | Direct |
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_pmd_pcm_1EC6C50, 255, 0, 255, 216 @ 100 | Direct |
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_pmd_pcm_1EC7C70, 255, 0, 255, 216 @ 101 | Direct |
	voice_noise_alt 60, 0, 0, 0, 1, 0, 0 @ 102 | Noise |
	voice_directsound_no_resample 68, 64, DirectSoundWaveData_pmd_pcm_1EC93A4, 255, 0, 255, 216 @ 103 | Direct |
	voice_noise_alt 60, 0, 0, 0, 1, 0, 0 @ 104 | Noise |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 105 | Square-1 | --
	voice_directsound_no_resample 68, 64, DirectSoundWaveData_pmd_pcm_1EB5878, 255, 0, 255, 216 @ 106 | Direct |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 107 | Square-1 | --
	voice_directsound_no_resample 68, 34, DirectSoundWaveData_pmd_pcm_1ECAAD4, 64, 226, 0, 0 @ 108 | Direct |
	voice_directsound_no_resample 68, 64, DirectSoundWaveData_pmd_pcm_1ECAAD4, 255, 226, 0, 0 @ 109 | Direct |
	voice_directsound_no_resample 68, 94, DirectSoundWaveData_pmd_pcm_1ECAAD4, 64, 226, 0, 0 @ 110 | Direct |
	voice_noise_alt 60, 0, 0, 0, 2, 0, 0 @ 111 | Noise |
	voice_noise_alt 60, 0, 0, 0, 2, 6, 0 @ 112 | Noise |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 113 | Square-1 | --
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_pmd_pcm_1EBA840, 255, 0, 255, 216 @ 114 | Direct |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 115 | Square-1 | --
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_pmd_pcm_1ECBB2C, 255, 0, 255, 216 @ 116 | Direct |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 117 | Square-1 | --
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_pmd_pcm_1EBE6E0, 255, 0, 255, 216 @ 118 | Direct |
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 119 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 120 | Square-1 | --
	voice_directsound_no_resample 60, 44, DirectSoundWaveData_pmd_pcm_1EBB32C, 255, 0, 255, 204 @ 121 | Direct |
	voice_directsound_no_resample 60, 84, DirectSoundWaveData_pmd_pcm_1EBBDCC, 255, 0, 255, 204 @ 122 | Direct |
	voice_directsound_no_resample 60, 44, DirectSoundWaveData_pmd_pcm_1EBC208, 255, 0, 255, 204 @ 123 | Direct |
	voice_directsound_no_resample 60, 84, DirectSoundWaveData_pmd_pcm_1EBD1D4, 255, 0, 255, 204 @ 124 | Direct |
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_pmd_pcm_1EADC80, 255, 0, 255, 216 @ 125 | Direct |
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_pmd_pcm_1EB0490, 255, 0, 255, 127 @ 126 | Direct |
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_pmd_pcm_1ECC450, 255, 0, 255, 0 @ 127 | Direct |
